### ISSUE TITLE
Wrongly calculated matched VA offsets when applying Yara rule

### ISSUE THREAD

**Issue by Dump-GUY** [rizinorg/rz-libyara#3]
**Environment information**
* Operating System: Windows 10 Pro 10.0.19044, Ubuntu 20.04
* Cutter version: 2.1.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: PE32, PE32+(64bit)

**Describe the bug**

Bug in wrongly calculating VA offset of matched applied Yara rule - the VA offset is wrongly calculated for Yara pattern types: "Bytes", "Assembly Raw", "Assembly Masked". The matched VA offset is correctly calculated when matching type string. Probably wrong calculation of matched VA offset when the matched pattern resides in code section..

Tested also for the same binary when applied more Yara rules...for all of them the wrongly matched VA has the same offset added...
Ex. like correctly matched VA for the same one binary is 00401010 and wrong is ex. 00406010, correct 00403062 - wrong 00408062 so somewhere in code wrong offset of 00005000 (in this case for this binary) is added...

**Screenshots**

Creation of Yara rule is OK:

![Yara_rule_creation_OK](https://user-images.githubusercontent.com/59492005/176980231-fc05fdb7-f9e2-4b52-a509-489ec9871255.png)

![New_created_YARA_Rule_VAoffset_OK](https://user-images.githubusercontent.com/59492005/176980292-12db6065-73d2-4d33-8c01-1cee584f448d.png)

Here BUG in wrongly calculated VA offset of matched pattern of Yara rule:

![BUG_wrongly_calculated_VAoffset_when_matching_YARA](https://user-images.githubusercontent.com/59492005/176980310-0e5ab671-b9b1-46dc-8ad8-72c3c5fae55b.png)

**Comment by Dump-GUY** [comment]
I am attaching the test sample used in this issue report. Its not malicious, just testing sample.
[Test_file.zip](https://github.com/rizinorg/rz-libyara/files/9070959/Test_file.zip)
.

**Comment by wargio** [comment]
Fixed via https://github.com/rizinorg/rz-libyara/commit/24d9a10ad8be2149e73a6a3065686cae2d9badf5

**Comment by Dump-GUY** [comment]
I thought that problem will be somewhere with rz_io_p2v but was not sure. Good job, tested and works well with both PE32/64 👍
